[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーム
[[plugins]]
repo = 'aradunovic/perun.vim'
hook_add = '''
  set termguicolors
  colorscheme perun
'''

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " 不可視ファイルの可視化
  let NERDTreeShowHidden = 1
  " ブックマーク表示
  let g:NERDTreeShowBookmarks=1
  " NERDTreeの開閉キーマップ
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

# NERDTreeをTab間で共有
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
if argc() == 0
  " ファイルが指定されていなければNERD treeを有効にする
  let g:nerdtree_tabs_open_on_console_startup = 1
end
'''

# NERDTreeにGit変更を表示
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# ステータスバー
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  let g:lightline = {
  \ 'colorscheme': 'jellybeans',
  \ }
'''

# インデントライン
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_color_term = 236
  let g:indentLine_color_gui = '#333333'
'''

# snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

