# 空白削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_i = 1
hook_post_source = 'autocmd BufWritePre * :FixWhitespace'

# 括弧自動補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_source = '''
  call lexima#add_rule({
    \ 'char': '<CR>',
    \ 'at': '{\%#}',
    \ 'input': '<CR>',
    \ 'input_after': '<CR>',
    \ 'filetype': 'javascript'
  \ })
'''

# tomlシンタックス
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# vueシンタックス
[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# 自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
on_ft = ['snippet']
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

